### ISSUE TITLE
Subscriber and Publisher

### ISSUE THREAD

**Issue by Iain-Stevenson** [loekd/ServiceFabric.PubSubActors#24]
I am having considerable trouble configuring one of my subscribers to also be a publisher.

I have confirmed that if I try and construct a PublisherServiceHelper inside of a StatelessService that is already a publisher, the Service will not start and the cluster goes into an unhealthy state.

I also cannot get Service Fabric Health Monitoring or full blown tell 'me everything 'mode Exception settings to unearth what is going on.

**Comment by Iain-Stevenson** [comment]
I will put together and post a solution that demonstrates the problem.

**Comment by Iain-Stevenson** [comment]
I am delighted to say my 'investigation' produced a working Subscriber Publishing as well. 

So I am closing this off. I shall now find out why my project was failing with this solution as an example.

I have posted the working solution, for posterity and to help others. [SF.Example.zip](https://github.com/loekd/ServiceFabric.PubSubActors/files/1000574/SF.Example.zip)

Its a trimmed down model of .NET Core API Controller publishing both notifications and Metrics  messages to two subscribers, the Metrics Subscriber also Publishing Notifications which are picked up by a common Communications subscriber.

It also shows an easy way to access the service Pub Logic from inside any API controller by passing a reference to itself in the API services.

I **was** wondering if the mix of .NET core and non Core projects was to blame for my problems but apparently not. When I discover why I had the original problem I will update it here to aid others.

**Comment by loekd** [comment]
Awesome! Thanks for this contribution. Due to attending the Build conference, my response is a bit late. Glad you got it working.

**Comment by Iain-Stevenson** [comment]
This is a bit of a TL:DR but might be worth it. 

It took some work but I found what the problem was. But I still don't **really** know why it happened.

It also explains why my provided sample worked and my production code did not. _they were different contracts_.

My Publishing Interface had two overrides of a method (One passing an additional Exception parameter) and did not uniquely name them in the Contract. This caused a Wcf exception to be emitted deep inside the Library that finally surfaced as an InvalidOperationException. 

# Cause

```
System.InvalidOperationException occurred
  HResult=0x80131509
  Message=Cannot have two operations in the same contract with the same name, methods PublishLogEntry and PublishLogEntry in type Project.Service.Messaging.ILogEntryPublisher violate this rule. You can change the name of one of the operations by changing the method name or by using the Name property of OperationContractAttribute.
  Source=System.ServiceModel
  StackTrace:
   at System.ServiceModel.Description.TypeLoader.CreateOperationDescription(ContractDescription contractDescription, MethodInfo methodInfo, MessageDirection direction, ContractReflectionInfo reflectionInfo, ContractDescription declaringContract)
   at System.ServiceModel.Description.TypeLoader.CreateOperationDescriptions(ContractDescription contractDescription, ContractReflectionInfo reflectionInfo, Type contractToGetMethodsFrom, ContractDescription declaringContract, MessageDirection direction)
   at System.ServiceModel.Description.TypeLoader.CreateContractDescription(ServiceContractAttribute contractAttr, Type contractType, Type serviceType, ContractReflectionInfo& reflectionInfo, Object serviceImplementation)
   at System.ServiceModel.Description.TypeLoader.LoadContractDescriptionHelper(Type contractType, Type serviceType, Object serviceImplementation)
   at System.ServiceModel.Description.ContractDescription.GetContract(Type contractType, Object serviceImplementation)
   at System.ServiceModel.ServiceHost.CreateDescription(IDictionary`2& implementedContracts)
   at System.ServiceModel.ServiceHostBase.InitializeDescription(UriSchemeKeyedCollection baseAddresses)
   at System.ServiceModel.ServiceHost..ctor(Object singletonInstance, Uri[] baseAddresses)
   at Microsoft.ServiceFabric.Services.Communication.Wcf.Runtime.WcfCommunicationListener`1.CreateServiceHost(Object wcfServiceObject, ServiceEndpoint endpoint)
   at Microsoft.ServiceFabric.Services.Communication.Wcf.Runtime.WcfCommunicationListener`1..ctor(ServiceContext serviceContext, TServiceContract wcfServiceObject, Binding listenerBinding, EndpointAddress address, String endpointResourceName)
   at Microsoft.ServiceFabric.Services.Communication.Wcf.Runtime.WcfCommunicationListener`1..ctor(ServiceContext serviceContext, TServiceContract wcfServiceObject, Binding listenerBinding, String endpointResourceName)
   at ServiceFabric.PubSubActors.SubscriberServices.SubscriberCommunicationListener.OpenAsync(CancellationToken cancellationToken) in D:\....\ServiceFabric.PubSubActors\SubscriberServices\SubscriberCommunicationListener.cs:line 51
   at Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.<OpenCommunicationListenersAsync>d__13.MoveNext()

```

That prevented the OnOpenAsync being called in my Publishing Subscriber and stopped the StatelessService from Registering itself with the Broker.

This all sounds reasonable (in a broken sense) but the issue I have now is trying to figure out why I did not get the exception being observed until after a great deal of work;

This exception failed to emerge for days of struggle, and many attempts to find it, even after switching on full 'Break when thrown' exception handling settings before starting the cluster, relentless code cleans/ rebuilds and local cluster refreshes.....

# How I got there

My Solution was a Mixture of .NET Core API/Web Site/Libraries and classic SF Stateless PubSub services.
Running on a 5 node local cluster under https with shared port 443 and each public service using a Url Suffix although I don't think that made a scrap of difference.

I'm not sure what of these were actually necessary in the end but , for posterity and those with similar problems here is what I actually did to solve it;

- I scrubbed the Classic PubSub 'Stateless' Services and rebuilt them all as .NET Core using the blank .NET Core template. (Don't have ReSharper switched on when you do that)
- I Left my Broker service as a  classic StatefulService
- I revisited all my projects and aligned them with the 'net452' framework as the FIRST framework in the <frameworks> tag of the csproj file.
- I forced all my projects referenced in the SF library chain to target x64
- I pulled the code from this library added Actors and Interfaces projects to my solution and modified my code copy to target only net452 in thier csproj files. Was 'net451;net46'

I would STRONGLY advise switching off ReSharper whislt you do that.

That is when I finally got the clue as to what was happening and only then did I get to move forward. 
# Conclusions
My belief is that it was a combination of framework and architecture targeting problems which failed to surface in compilation and deployment and the SF run time and the above exception never had a chance to emerge until after I aligned all of the projects correctly. If that is true its a really bizzare problem.

A cautionary note here and something that gave me the idea, is that if you multi target frameworks using the <frameworks> tag (I.e. not the single <framework> tag) in your csproj file, the FIRST framework in the list is the one that gets the conditional keyword in the project properties?!

# Alert

  ```
/// <summary>
/// Optional override to create listeners (e.g., TCP, HTTP) for this service replica to handle client or user requests.
/// </summary>
/// <returns>A collection of listeners.</returns>
protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()
{
	yield return new ServiceInstanceListener(p => new SubscriberCommunicationListener(this, p), "AgentCommunicationListener");
	yield return new ServiceInstanceListener(context => new FabricTransportServiceRemotingListener(context, this), "AgentFabricTransportServiceRemotingListener");
}
```

The order of those listener's is important.

If you invert them (as I tried to in desperation at one point). You get a different exception related to http/net.tcp transports. The above is the correct order

# Summary
Solving this has cost me ~7 days of effort in all. 

I would have given up with this had it not been for 2 things, a) my absolute belief that I was the cause and I could fix it, and b)  my option to switch to the source code version and tinker with the targeting, and which just shows how important it can be to get hold of the source code in such cases.  

So a massive **thank you** for making the source code available.

This has been a bit of a learning curve. I'm not entirely sure I have learned the right lessons. lol
